upvcarshare/config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views import defaults as default_views
from django.views.i18n import javascript_catalog

from config.router import urlpatterns as api_urlpatterns
from core.views import PartialsTemplateView
from pages.views import HomeView

urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^", include("pages.urls", namespace="pages")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^journeys/", include("journeys.urls", namespace="journeys")),
    url(r"^notifications/", include("notifications.urls", namespace="notifications")),
]

# Partials URLs
urlpatterns += [
    url(r'^partials/(?P<name>.+)\.html', PartialsTemplateView.as_view(), name="partials-template"),
]

# OpenID URLs
urlpatterns += [
    url(r"^accounts/signup/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r"^accounts/login/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r"^accounts/logout/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r'^accounts/', include('allauth.urls')),
]

# Admin URLs
admin.site.site_header = _('UPV Car Share Admin')
urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

# API URLs
# Create a router and register our resources with it.
urlpatterns += [
    url(r'^api/v1/', include(api_urlpatterns, namespace="api_v1")),
]

# JavaScript i18n
js_info_dict = {
    'packages': ('recurrence', ),
}
urlpatterns += [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    # Media URLs on debug
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upvcarshare/journeys/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

from django.conf.urls import url

from journeys.views.journeys import RecommendedJourneyView, JourneysView, CreateJourneyView, EditJourneyView, \
    CancelJourneyView, JoinJourneyView, LeaveJourneyView, ConfirmJourneyView, RejectJourneyView, \
    ThrowOutPassengerView, JourneyView, DeleteJourneyView, SearchJourneysView, DeleteAllJourneyView
from journeys.views.places import CreateResidenceView, EditResidenceView, DeleteResidence, CurrentUserResidencesView
from journeys.views.transports import CreateTransportView, EditTransportView, DeleteTransportView, TransportListView

urlpatterns = [
    # Residences
    url(r"residences/create/$", CreateResidenceView.as_view(), name="create-residence"),
    url(r"residences/(?P<pk>\d+)/edit/$", EditResidenceView.as_view(), name="edit-residence"),
    url(r"residences/(?P<pk>\d+)/delete/$", DeleteResidence.as_view(), name="delete-residence"),
    url(r"residences/$", CurrentUserResidencesView.as_view(), name="residences"),

    # Transports
    url(r"transports/create/$", CreateTransportView.as_view(), name="create-transport"),
    url(r"transports/(?P<pk>\d+)/edit/$", EditTransportView.as_view(), name="edit-transport"),
    url(r"transports/(?P<pk>\d+)/delete/$", DeleteTransportView.as_view(), name="delete-transport"),
    url(r"transports/$", TransportListView.as_view(), name="transports"),

    # Journeys
    url(r"search/$", SearchJourneysView.as_view(), name="search"),
    url(r"recommended/$", RecommendedJourneyView.as_view(), name="recommended"),
    url(r"create/$", CreateJourneyView.as_view(), name="create"),
    url(r"(?P<pk>\d+)/edit/$", EditJourneyView.as_view(), name="edit"),
    url(r"(?P<pk>\d+)/cancel/$", CancelJourneyView.as_view(), name="cancel"),
    url(r"(?P<pk>\d+)/delete/$", DeleteJourneyView.as_view(), name="delete"),
    url(r"(?P<pk>\d+)/delete-all/$", DeleteAllJourneyView.as_view(), name="delete-all"),
    url(r"(?P<pk>\d+)/join/$", JoinJourneyView.as_view(), name="join"),
    url(r"(?P<pk>\d+)/leave/$", LeaveJourneyView.as_view(), name="leave"),
    url(r"(?P<pk>\d+)/confirm/$", ConfirmJourneyView.as_view(), name="confirm"),
    url(r"(?P<pk>\d+)/reject/$", RejectJourneyView.as_view(), name="reject"),
    url(r"(?P<pk>\d+)/throw-out/$", ThrowOutPassengerView.as_view(), name="throw-out"),
    url(r"(?P<pk>\d+)/$", JourneyView.as_view(), name="details"),
    url(r"$", JourneysView.as_view(), name="list"),

]

upvcarshare/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

urlpatterns = [
]

upvcarshare/journeys/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

import datetime
from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from journeys import GOING
from journeys.exceptions import AlreadyAPassenger, NoFreePlaces, NotAPassenger
from journeys.forms import JourneyForm, ResidenceForm, FilterForm, CancelJourneyForm, SmartJourneyForm, \
    ConfirmRejectJourneyForm, TransportForm
from journeys.models import Journey, Residence, Campus, Passenger, Transport


class CreateResidenceView(LoginRequiredMixin, View):
    """View to show journey creation form and to handle its creation."""

    template_name = "residences/create.html"

    def get(self, request):
        initial = {
            "address": request.user.default_address,
            "position": request.user.default_position,
            "distance": request.user.default_distance,
        }
        form = ResidenceForm(initial=initial)
        data = {
            "form": form
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = ResidenceForm(request.POST)
        data = {
            "form": form
        }
        if form.is_valid():
            residence = form.save(user=request.user)
            return redirect("journeys:edit-residence", pk=residence.pk)
        return render(request, self.template_name, data)


class EditResidenceView(LoginRequiredMixin, View):
    """View to edit residences."""

    template_name = "residences/edit.html"

    def get(self, request, pk):
        residence = get_object_or_404(Residence, pk=pk, user=request.user)
        form = ResidenceForm(instance=residence)
        data = {
            "form": form,
            "residence": residence,
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        residence = get_object_or_404(Residence, pk=pk, user=request.user)
        form = ResidenceForm(request.POST, instance=residence)
        data = {
            "form": form,
            "residence": residence,
        }
        if form.is_valid():
            form.save(user=request.user)
        return render(request, self.template_name, data)


class CreateJourneyView(LoginRequiredMixin, View):
    """View to show journey creation form and to handle its creation."""

    template_name = "journeys/create.smart.html"
    form = SmartJourneyForm

    def get(self, request):
        residences = Residence.objects.filter(user=request.user)
        campuses = Campus.objects.all()
        initial_departure = timezone.now().replace(second=0, minute=0) + datetime.timedelta(hours=1)
        initial = {
            "residence": residences.first() if residences.exists() else None,
            "campus": campuses.first() if campuses.exists() else None,
            "kind": GOING,
            "departure": initial_departure,
            "arrival": initial_departure + datetime.timedelta(minutes=30)
        }
        form = self.form(initial=initial, user=request.user)
        data = {
            "form": form
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = self.form(request.POST, user=request.user)
        data = {
            "form": form
        }
        if form.is_valid():
            journey = form.save()
            return redirect("journeys:details", pk=journey.pk)
        return render(request, self.template_name, data)


class EditJourneyView(LoginRequiredMixin, View):
    """View to edit journeys."""

    template_name = "journeys/edit.html"

    def get(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk, user=request.user)
        form = JourneyForm(
            instance=journey,
            initial={"i_am_driver": journey.driver is not None and journey.driver == request.user},
            user=request.user
        )
        data = {
            "form": form,
            "journey": journey,
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk, user=request.user)
        form = JourneyForm(request.POST, instance=journey, user=request.user)
        data = {
            "form": form,
            "journey": journey,
        }
        if form.is_valid():
            form.save()
            return redirect("journeys:details", pk=journey.pk)
        return render(request, self.template_name, data)


class JourneyView(LoginRequiredMixin, View):
    """View to journey details."""

    template_name = "journeys/details.html"

    @staticmethod
    def show_passengers(request, journey):
        if journey.user == request.user:
            return True
        return journey.is_passenger(request.user) and journey.count_passengers() > 0 and not journey.needs_driver()

    @staticmethod
    def show_messenger(request, journey):
        if journey.user == request.user and not journey.needs_driver():
            return True
        return journey.is_passenger(request.user)

    def get(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk)
        data = {
            "journey": journey,
            "show_passengers": self.show_passengers(request, journey),
            "show_messenger": self.show_messenger(request, journey),
            "is_fulfilled": journey.is_fulfilled(),
            "fulfilled_by": journey.fulfilled_by(),
            "passengers": journey.passengers_list(request.user),
            "recommended": journey.recommended(),
        }
        return render(request, self.template_name, data)


class RecommendedJourneyView(LoginRequiredMixin, View):
    """View to show to the user the list of recommended journeys according to his needs."""
    template_name = "journeys/recommended.html"

    def get(self, request):
        filter_form = FilterForm(request.GET)
        kind_filter = None
        override_distance = None
        if filter_form.is_valid():
            kind_filter = filter_form.cleaned_data.get("kind")
            override_distance = filter_form.cleaned_data.get("distance")
        data = {
            "filter_form": filter_form,
            "journeys": Journey.objects.recommended(
                user=request.user,
                kind=kind_filter,
                override_distance=override_distance
            ),
        }
        return render(request, self.template_name, data)


class JourneysView(LoginRequiredMixin, View):
    """View to show to the user the list of his created journeys."""
    template_name = "journeys/list.html"

    def get(self, request):
        journeys = Journey.objects.filter(user=request.user).order_by("departure")
        data = {
            "journeys": journeys,
            "journeys_count": journeys.count()
        }
        return render(request, self.template_name, data)


class CurrentUserResidencesView(LoginRequiredMixin, View):
    """View to show to the user the list of his created residences."""

    template_name = "residences/list.html"

    def get(self, request):
        data = {
            "residences": Residence.objects.filter(user=request.user)
        }
        return render(request, self.template_name, data)


# class PassengerJourneyView(LoginRequiredMixin, View):
#     """View to show the list of journeys where the user is passenger."""
#     template_name = "journeys/passenger.html"
#
#     def get(self, request):
#         data = {
#             "journeys": Journey.objects.passenger(user=request.user)
#         }
#         return render(request, self.template_name, data)


class JoinJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk)
        try:
            journey.join_passenger(request.user)
            messages.success(request, _('Has solicitado unirte al trayecto'))
        except AlreadyAPassenger:
            messages.error(request, _('¡Ya has solicitado unirte al trayecto!'))
        except NoFreePlaces:
            messages.error(request, _('No quedan plazas libres en el trayecto'))
        return_to = request.POST.get("return_to", self.return_to)
        return redirect(return_to)


class ConfirmJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        passenger = get_object_or_404(Passenger, pk=pk)
        if passenger.journey.user != request.user:
            raise Http404
        form = ConfirmRejectJourneyForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            try:
                passenger.journey.confirm_passenger(user)
            except NotAPassenger:
                messages.success(request, _('El usuario no está en este trayecto'))
        return_to = request.POST.get("return_to", self.return_to)
        return redirect(return_to)


class RejectJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        passenger = get_object_or_404(Passenger, pk=pk)
        if passenger.journey.user != request.user:
            raise Http404
        form = ConfirmRejectJourneyForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            try:
                passenger.journey.reject_passenger(user)
            except NotAPassenger:
                messages.success(request, _('El usuario no está en este trayecto'))
        return_to = request.POST.get("return_to", self.return_to)

upvcarshare/journeys/views/transports.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from journeys.forms import TransportForm
from journeys.models import Transport


class TransportListView(LoginRequiredMixin, View):
    """Shows the list of users' transports."""
    template_name = "transports/list.html"

    def get(self, request):
        data = {
            "transports": Transport.objects.filter(user=request.user)
        }
        return render(request, self.template_name, data)


class CreateTransportView(LoginRequiredMixin, View):
    """Handles the creation of a new transport."""
    template_name = "transports/create.html"
    form = TransportForm

    def get(self, request):
        data = {
            "form": self.form(user=request.user)
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = self.form(request.POST, user=request.user)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request, _('Has creado el transporte correctamente'))
            return redirect("journeys:transports")
        data = {"form": form}
        return render(request, self.template_name, data)


class EditTransportView(LoginRequiredMixin, View):
    """Handles the edition of a new transport."""
    template_name = "transports/edit.html"
    form = TransportForm

    def get(self, request, pk):
        transport = get_object_or_404(Transport, pk=pk, user=request.user)
        data = {
            "form": self.form(instance=transport, user=request.user),
            "transport": transport
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        transport = get_object_or_404(Transport, pk=pk, user=request.user)
        form = self.form(request.POST, user=request.user, instance=transport)
        if form.is_valid():
            messages.success(request, _('Has editado el transporte correctamente'))
            return redirect("journeys:transports")
        data = {
            "form": form,
            "transport": transport
        }
        return render(request, self.template_name, data)


class DeleteTransportView(LoginRequiredMixin, View):
    pass

upvcarshare/templates/journeys/cancel.html
{% extends "header.html" %}
{% load i18n %}

{% block section_title %}
    <div class="row">
        <div class="col-xs-12">
            <h2>
                <strong>{% trans "Cancelar" %}</strong>: {{ journey.description }}, {{ journey.departure }}
            </h2>
        </div>
    </div>
{% endblock section_title %}

{% block content %}
    <div class="row">
        <div class="col-sm-12 text-xs-center">
            <p class="lead">
                {% trans "¿Estás seguro que quieres cancelar este viaje? Esta acción no se puede deshacer" %}
            </p>
            <form method="post" action="">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">{% trans "Cancelar viaje" %}</button>
                <a href="{% url "journeys:details" journey.pk %}" class="btn btn-primary">{% trans "Volver" %}</a>
            </form>
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/create.html
{% extends "header.html" %}

{% load i18n %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block section_title %}
<div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Crear viaje" %}</h2>
    </div>
</div>
{% endblock section_title %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group row{% if field.errors %} has-danger{% endif %}">
                        <label for="{{ field.auto_id }}" class="col-sm-4 form-control-label">{{ field.label }}</label>
                        <div class="col-sm-8">
                        {% if field.name == "residence" %}
                            <div class="row">
                                <div class="col-sm-7">
                                    {{ field }}
                                </div>
                                <div class="col-sm-5">
                                    {% block residence_action %}
                                        <div class="btn-group float-xs-right" role="group" aria-label="{% trans "Acciones" %}">
                                            <a href="{% url "journeys:create-residence" %}" class="btn btn-success-outline">{% trans "Crear nuevo lugar" %}</a>
                                        </div>
                                    {% endblock %}
                                </div>
                            </div>
                        {% elif field.name == "departure" %}
                            <journey-datetime field-name="{{ field.name }}" field-id="{{ field.auto_id }}" value="{{ field.value|date:"c" }}"></journey-datetime>
                        {% elif field.name == "arrival" %}
                            <journey-datetime field-name="{{ field.name }}" field-id="{{ field.auto_id }}" value="{{ field.value|date:"c" }}"></journey-datetime>
                        {% else %}
                            {{ field }}
                        {% endif %}
                            <span class="text-muted">{{ field.help_text }}</span>
                            <span class="text-muted">{{ field.errors }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        {% block buttons %}
                        <button type="submit" class="btn btn-success">{% trans "Guardar" %}</button>
                        <a href="{% url "journeys:list" %}" class="btn btn-danger">{% trans "Volver" %}</a>
                        {% endblock buttons %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/create.smart.html
{% extends "header.html" %}

{% load i18n %}

{% block title %}{% trans "Crear viaje" %}{% endblock title %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block section_title %}
<div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Crear viaje" %}</h2>
    </div>
</div>
{% endblock section_title %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <form method="post" action="" journey-form>
                {% csrf_token %}
                <origin-destination-select
                        origin-field="{{ form.origin.name }}"
                        origin-field-id="{{ form.origin.auto_id }}"
                        destiny-field="{{ form.destiny.name }}"
                        destiny-field-id="{{ form.destiny.auto_id }}">
                </origin-destination-select>
                <div class="col-sm-offset-4 col-sm-8">
                  <span class="text-muted text-danger">{{ form.origin.errors }}</span>
                </div>
                {% for field in form %}
                    {% if not field.is_hidden %}
                    <div class="form-group row{% if field.errors %} has-danger{% endif %}" {% if field.name == "transport" or field.name == "free_places" %}ng-hide="iAmDriver == 'False'"{% elif field.name == "time_window" %}ng-hide="iAmDriver == 'True'"{% endif %}>
                        <label for="{{ field.auto_id }}" class="col-sm-4 form-control-label">{{ field.label }}</label>
                        <div class="col-sm-8">
                        {% if field.name == "residence" %}
                            <div class="row">
                                <div class="col-sm-7">
                                    {{ field }}
                                </div>
                                <div class="col-sm-5">
                                    {% block residence_action %}
                                        <div class="btn-group float-xs-right" role="group" aria-label="{% trans "Acciones" %}">
                                            <a href="{% url "journeys:create-residence" %}" class="btn btn-outline-success">{% trans "Crear nuevo lugar" %}</a>
                                        </div>
                                    {% endblock %}
                                </div>
                            </div>
                          {% elif field.name == "transport" %}
                                <div class="row">
                                    <div class="col-sm-7">
                                        {{ field }}
                                    </div>
                                    <div class="col-sm-5">
                                      <div class="btn-group float-xs-right" role="group" aria-label="{% trans "Acciones" %}">
                                        <a href="{% url "journeys:create-transport" %}" class="btn btn-outline-success">{% trans "Crear nuevo transporte" %}</a>
                                      </div>
                                    </div>
                                </div>
                        {% elif field.name == "departure" %}
                            <journey-datetime field-name="{{ field.name }}" field-id="{{ field.auto_id }}" value="{{ field.value|date:"c" }}" on-update="onUpdateDeparture(value)"></journey-datetime>
                        {% elif field.name == "arrival" %}
                            <journey-datetime field-name="{{ field.name }}" field-id="{{ field.auto_id }}" value="{{ field.value|date:"c" }}" override-value="newArrivalValue"></journey-datetime>
                        {% else %}
                            {{ field }}
                        {% endif %}
                            <span class="text-muted">{{ field.help_text }}</span>
                            <span class="text-muted text-danger">{{ field.errors }}</span>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-success">{% trans "Guardar" %}</button>
                        <a href="{% url "journeys:list" %}" class="btn btn-danger">{% trans "Volver" %}</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/edit.html
{% extends "journeys/create.html" %}
{% load i18n %}

{% block title %}{% trans "Editar viaje" %}{% endblock title %}

{% block section_title %}
<div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Editar viaje" %}</h2>
    </div>
</div>
{% endblock section_title %}

{% block residence_action %}
    <div class="btn-group float-xs-right" role="group" aria-label="{% trans "Acciones" %}">
        <a href="{% url "journeys:edit-residence" journey.residence.pk %}" class="btn btn-secondary">{% trans "Editar lugar" %}</a>
        <a href="{% url "journeys:create-residence" %}" class="btn btn-secondary">{% trans "Crear nuevo lugar" %}</a>
    </div>
{% endblock %}

{% block buttons %}
    <button type="submit" class="btn btn-success">{% trans "Guardar" %}</button>
    <a href="{% url "journeys:details" journey.pk %}" class="btn btn-danger">{% trans "Volver" %}</a>
{% endblock buttons %}

upvcarshare/templates/journeys/list.html
{% extends "header.html" %}
{% load i18n %}
{% load journeys_tags %}

{% block title %}{% trans "Mis viajes" %}{% endblock title %}

{% block section_title %}
    <div class="row">
        <div class="col-sm-10">
            <h2>{% trans "Mis viajes" %}</h2>
            <p>{% trans "Los viajes tanto que necesitas hacer a un campus y no tienes transporte como aquellos que quieres ofrecer transporte a otras personas." %}</p>
        </div>
        <div class="col-sm-2">
            <a href="{% url "journeys:create" %}" class="btn btn-primary">{% trans "Nuevo viaje" %}</a>
        </div>
    </div>
{% endblock section_title %}

{% block content %}
    {% if journeys_count == 0 %}
        <h3 class="text-muted">{% trans "No tienes viajes creados" %}</h3>
    {% endif %}
    <div class="row" style="margin-bottom: 15px">
        <div class="col-sm-12">
            <calendar user-id="{{ request.user.pk }}"></calendar>
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/passenger.html
{% extends "header.html" %}
{% load i18n %}
{% load journeys_tags %}

{% block section_title %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{% trans "Viajes en los que viajo" %}</h2>
            <p>{% trans "Lista con los viajes a los que te has apuntado como pasajero." %}</p>
        </div>
    </div>
{% endblock section_title %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            {% for journey in journeys %}
                {% journey_item journey %}
            {% empty %}
                <h3 class="text-muted">{% trans "No tienes viajes en los que viajas" %}</h3>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/recommended.html
{% extends "sidebar.html" %}
{% load i18n %}
{% load journeys_tags %}

{% block title %}{% trans "Viajes recomendados" %}{% endblock title %}

{% block section_title %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{% trans "Viajes recomendados" %}</h2>
            <p>{% trans "Lista con los viajes que ofrecen otras personas y que se adaptan a tus necesidades." %}</p>

        </div>
    </div>
{% endblock section_title %}

{% block sidebar %}
    <form method="get" action="" class="text-xs-left">
        {% for field in filter_form %}
            <div class="form-group{% if field.errors %} has-danger{% endif %}">
                <label for="{{ field.auto_id }}" class="form-control-label">{{ field.label }}</label>
                {{ field }}
                <span class="text-muted">{{ field.help_text }}</span>
                <span class="text-muted">{{ field.errors }}</span>
            </div>
        {% endfor %}
        <div class="form-group">
          <div class="btn-group-vertical">
            <button type="submit" class="btn btn-info">{% trans "Filtrar" %}</button>
            <a href="{% url "journeys:recommended" %}" class="btn btn-danger">{% trans "Quitar filtros" %}</a>
          </div>
        </div>
    </form>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            {% for journey in journeys %}
                {% journey_item journey %}
            {% empty %}
                <h3 class="text-muted">{% trans "No hemos encontrado viajes recomendados" %}</h3>
                <p class="lead">{% trans "Puedes crear los viajes en los que necesitas transporte para que te mostremos aquí una lista de conductores que pueden llevarte a tu destino." %}</p>
                <a href="{% url "journeys:create" %}" class="btn btn-lg btn-primary">{% trans "Crear viaje" %}</a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

upvcarshare/templates/journeys/user_list.html
{% extends "sidebar.html" %}
{% load i18n %}
{% load journeys_tags %}

{% block section_title %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{% trans "Mis viajes" %}</h2>
            <p>{% trans "Lista con los viajes tanto que necesitas hacer a un campus y no tienes transporte como aquellos que quieres ofrecer transporte a otras personas." %}</p>
        </div>
    </div>
{% endblock section_title %}

{% block sidebar %}
    <a href="{% url "journeys:create" %}" class="btn btn-primary">{% trans "Nuevo viaje" %}</a>
{% endblock sidebar %}

{% block content %}
    {% for journey in journeys %}
        {% journey_item journey %}
    {% empty %}
        <h3 class="text-muted">{% trans "No tienes viaje creados" %}</h3>
    {% endfor %}
{% endblock content %}