upvcarshare/config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views import defaults as default_views
from django.views.i18n import javascript_catalog

from config.router import urlpatterns as api_urlpatterns
from core.views import PartialsTemplateView
from pages.views import HomeView

urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^", include("pages.urls", namespace="pages")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^journeys/", include("journeys.urls", namespace="journeys")),
    url(r"^notifications/", include("notifications.urls", namespace="notifications")),
]

# Partials URLs
urlpatterns += [
    url(r'^partials/(?P<name>.+)\.html', PartialsTemplateView.as_view(), name="partials-template"),
]

# OpenID URLs
urlpatterns += [
    url(r"^accounts/signup/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r"^accounts/login/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r"^accounts/logout/$", default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
    url(r'^accounts/', include('allauth.urls')),
]

# Admin URLs
admin.site.site_header = _('UPV Car Share Admin')
urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

# API URLs
# Create a router and register our resources with it.
urlpatterns += [
    url(r'^api/v1/', include(api_urlpatterns, namespace="api_v1")),
]

# JavaScript i18n
js_info_dict = {
    'packages': ('recurrence', ),
}
urlpatterns += [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    # Media URLs on debug
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upvcarshare/journeys/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

from django.conf.urls import url

from journeys.views.journeys import RecommendedJourneyView, JourneysView, CreateJourneyView, EditJourneyView, \
    CancelJourneyView, JoinJourneyView, LeaveJourneyView, ConfirmJourneyView, RejectJourneyView, \
    ThrowOutPassengerView, JourneyView, DeleteJourneyView, SearchJourneysView, DeleteAllJourneyView
from journeys.views.places import CreateResidenceView, EditResidenceView, DeleteResidence, CurrentUserResidencesView
from journeys.views.transports import CreateTransportView, EditTransportView, DeleteTransportView, TransportListView

urlpatterns = [
    # Residences
    url(r"residences/create/$", CreateResidenceView.as_view(), name="create-residence"),
    url(r"residences/(?P<pk>\d+)/edit/$", EditResidenceView.as_view(), name="edit-residence"),
    url(r"residences/(?P<pk>\d+)/delete/$", DeleteResidence.as_view(), name="delete-residence"),
    url(r"residences/$", CurrentUserResidencesView.as_view(), name="residences"),

    # Transports
    url(r"transports/create/$", CreateTransportView.as_view(), name="create-transport"),
    url(r"transports/(?P<pk>\d+)/edit/$", EditTransportView.as_view(), name="edit-transport"),
    url(r"transports/(?P<pk>\d+)/delete/$", DeleteTransportView.as_view(), name="delete-transport"),
    url(r"transports/$", TransportListView.as_view(), name="transports"),

    # Journeys
    url(r"search/$", SearchJourneysView.as_view(), name="search"),
    url(r"recommended/$", RecommendedJourneyView.as_view(), name="recommended"),
    url(r"create/$", CreateJourneyView.as_view(), name="create"),
    url(r"(?P<pk>\d+)/edit/$", EditJourneyView.as_view(), name="edit"),
    url(r"(?P<pk>\d+)/cancel/$", CancelJourneyView.as_view(), name="cancel"),
    url(r"(?P<pk>\d+)/delete/$", DeleteJourneyView.as_view(), name="delete"),
    url(r"(?P<pk>\d+)/delete-all/$", DeleteAllJourneyView.as_view(), name="delete-all"),
    url(r"(?P<pk>\d+)/join/$", JoinJourneyView.as_view(), name="join"),
    url(r"(?P<pk>\d+)/leave/$", LeaveJourneyView.as_view(), name="leave"),
    url(r"(?P<pk>\d+)/confirm/$", ConfirmJourneyView.as_view(), name="confirm"),
    url(r"(?P<pk>\d+)/reject/$", RejectJourneyView.as_view(), name="reject"),
    url(r"(?P<pk>\d+)/throw-out/$", ThrowOutPassengerView.as_view(), name="throw-out"),
    url(r"(?P<pk>\d+)/$", JourneyView.as_view(), name="details"),
    url(r"$", JourneysView.as_view(), name="list"),

]

upvcarshare/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

urlpatterns = [
]

upvcarshare/journeys/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

import datetime
from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from journeys import GOING
from journeys.exceptions import AlreadyAPassenger, NoFreePlaces, NotAPassenger
from journeys.forms import JourneyForm, ResidenceForm, FilterForm, CancelJourneyForm, SmartJourneyForm, \
    ConfirmRejectJourneyForm, TransportForm
from journeys.models import Journey, Residence, Campus, Passenger, Transport


class CreateResidenceView(LoginRequiredMixin, View):
    """View to show journey creation form and to handle its creation."""

    template_name = "residences/create.html"

    def get(self, request):
        initial = {
            "address": request.user.default_address,
            "position": request.user.default_position,
            "distance": request.user.default_distance,
        }
        form = ResidenceForm(initial=initial)
        data = {
            "form": form
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = ResidenceForm(request.POST)
        data = {
            "form": form
        }
        if form.is_valid():
            residence = form.save(user=request.user)
            return redirect("journeys:edit-residence", pk=residence.pk)
        return render(request, self.template_name, data)


class EditResidenceView(LoginRequiredMixin, View):
    """View to edit residences."""

    template_name = "residences/edit.html"

    def get(self, request, pk):
        residence = get_object_or_404(Residence, pk=pk, user=request.user)
        form = ResidenceForm(instance=residence)
        data = {
            "form": form,
            "residence": residence,
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        residence = get_object_or_404(Residence, pk=pk, user=request.user)
        form = ResidenceForm(request.POST, instance=residence)
        data = {
            "form": form,
            "residence": residence,
        }
        if form.is_valid():
            form.save(user=request.user)
        return render(request, self.template_name, data)


class CreateJourneyView(LoginRequiredMixin, View):
    """View to show journey creation form and to handle its creation."""

    template_name = "journeys/create.smart.html"
    form = SmartJourneyForm

    def get(self, request):
        residences = Residence.objects.filter(user=request.user)
        campuses = Campus.objects.all()
        initial_departure = timezone.now().replace(second=0, minute=0) + datetime.timedelta(hours=1)
        initial = {
            "residence": residences.first() if residences.exists() else None,
            "campus": campuses.first() if campuses.exists() else None,
            "kind": GOING,
            "departure": initial_departure,
            "arrival": initial_departure + datetime.timedelta(minutes=30)
        }
        form = self.form(initial=initial, user=request.user)
        data = {
            "form": form
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = self.form(request.POST, user=request.user)
        data = {
            "form": form
        }
        if form.is_valid():
            journey = form.save()
            return redirect("journeys:details", pk=journey.pk)
        return render(request, self.template_name, data)


class EditJourneyView(LoginRequiredMixin, View):
    """View to edit journeys."""

    template_name = "journeys/edit.html"

    def get(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk, user=request.user)
        form = JourneyForm(
            instance=journey,
            initial={"i_am_driver": journey.driver is not None and journey.driver == request.user},
            user=request.user
        )
        data = {
            "form": form,
            "journey": journey,
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk, user=request.user)
        form = JourneyForm(request.POST, instance=journey, user=request.user)
        data = {
            "form": form,
            "journey": journey,
        }
        if form.is_valid():
            form.save()
            return redirect("journeys:details", pk=journey.pk)
        return render(request, self.template_name, data)


class JourneyView(LoginRequiredMixin, View):
    """View to journey details."""

    template_name = "journeys/details.html"

    @staticmethod
    def show_passengers(request, journey):
        if journey.user == request.user:
            return True
        return journey.is_passenger(request.user) and journey.count_passengers() > 0 and not journey.needs_driver()

    @staticmethod
    def show_messenger(request, journey):
        if journey.user == request.user and not journey.needs_driver():
            return True
        return journey.is_passenger(request.user)

    def get(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk)
        data = {
            "journey": journey,
            "show_passengers": self.show_passengers(request, journey),
            "show_messenger": self.show_messenger(request, journey),
            "is_fulfilled": journey.is_fulfilled(),
            "fulfilled_by": journey.fulfilled_by(),
            "passengers": journey.passengers_list(request.user),
            "recommended": journey.recommended(),
        }
        return render(request, self.template_name, data)


class RecommendedJourneyView(LoginRequiredMixin, View):
    """View to show to the user the list of recommended journeys according to his needs."""
    template_name = "journeys/recommended.html"

    def get(self, request):
        filter_form = FilterForm(request.GET)
        kind_filter = None
        override_distance = None
        if filter_form.is_valid():
            kind_filter = filter_form.cleaned_data.get("kind")
            override_distance = filter_form.cleaned_data.get("distance")
        data = {
            "filter_form": filter_form,
            "journeys": Journey.objects.recommended(
                user=request.user,
                kind=kind_filter,
                override_distance=override_distance
            ),
        }
        return render(request, self.template_name, data)


class JourneysView(LoginRequiredMixin, View):
    """View to show to the user the list of his created journeys."""
    template_name = "journeys/list.html"

    def get(self, request):
        journeys = Journey.objects.filter(user=request.user).order_by("departure")
        data = {
            "journeys": journeys,
            "journeys_count": journeys.count()
        }
        return render(request, self.template_name, data)


class CurrentUserResidencesView(LoginRequiredMixin, View):
    """View to show to the user the list of his created residences."""

    template_name = "residences/list.html"

    def get(self, request):
        data = {
            "residences": Residence.objects.filter(user=request.user)
        }
        return render(request, self.template_name, data)


# class PassengerJourneyView(LoginRequiredMixin, View):
#     """View to show the list of journeys where the user is passenger."""
#     template_name = "journeys/passenger.html"
#
#     def get(self, request):
#         data = {
#             "journeys": Journey.objects.passenger(user=request.user)
#         }
#         return render(request, self.template_name, data)


class JoinJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        journey = get_object_or_404(Journey, pk=pk)
        try:
            journey.join_passenger(request.user)
            messages.success(request, _('Has solicitado unirte al trayecto'))
        except AlreadyAPassenger:
            messages.error(request, _('¡Ya has solicitado unirte al trayecto!'))
        except NoFreePlaces:
            messages.error(request, _('No quedan plazas libres en el trayecto'))
        return_to = request.POST.get("return_to", self.return_to)
        return redirect(return_to)


class ConfirmJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        passenger = get_object_or_404(Passenger, pk=pk)
        if passenger.journey.user != request.user:
            raise Http404
        form = ConfirmRejectJourneyForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            try:
                passenger.journey.confirm_passenger(user)
            except NotAPassenger:
                messages.success(request, _('El usuario no está en este trayecto'))
        return_to = request.POST.get("return_to", self.return_to)
        return redirect(return_to)


class RejectJourneyView(LoginRequiredMixin, View):
    """View to handle the action of joining a journey. """
    return_to = "journeys:recommended"

    def post(self, request, pk):
        passenger = get_object_or_404(Passenger, pk=pk)
        if passenger.journey.user != request.user:
            raise Http404
        form = ConfirmRejectJourneyForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            try:
                passenger.journey.reject_passenger(user)
            except NotAPassenger:
                messages.success(request, _('El usuario no está en este trayecto'))
        return_to = request.POST.get("return_to", self.return_to)

upvcarshare/journeys/views/transports.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, absolute_import

from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from journeys.forms import TransportForm
from journeys.models import Transport


class TransportListView(LoginRequiredMixin, View):
    """Shows the list of users' transports."""
    template_name = "transports/list.html"

    def get(self, request):
        data = {
            "transports": Transport.objects.filter(user=request.user)
        }
        return render(request, self.template_name, data)


class CreateTransportView(LoginRequiredMixin, View):
    """Handles the creation of a new transport."""
    template_name = "transports/create.html"
    form = TransportForm

    def get(self, request):
        data = {
            "form": self.form(user=request.user)
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = self.form(request.POST, user=request.user)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request, _('Has creado el transporte correctamente'))
            return redirect("journeys:transports")
        data = {"form": form}
        return render(request, self.template_name, data)


class EditTransportView(LoginRequiredMixin, View):
    """Handles the edition of a new transport."""
    template_name = "transports/edit.html"
    form = TransportForm

    def get(self, request, pk):
        transport = get_object_or_404(Transport, pk=pk, user=request.user)
        data = {
            "form": self.form(instance=transport, user=request.user),
            "transport": transport
        }
        return render(request, self.template_name, data)

    def post(self, request, pk):
        transport = get_object_or_404(Transport, pk=pk, user=request.user)
        form = self.form(request.POST, user=request.user, instance=transport)
        if form.is_valid():
            messages.success(request, _('Has editado el transporte correctamente'))
            return redirect("journeys:transports")
        data = {
            "form": form,
            "transport": transport
        }
        return render(request, self.template_name, data)


class DeleteTransportView(LoginRequiredMixin, View):
    pass

upvcarshare/templates/journeys/blocks/details.actions.html
{% load i18n %}
{% load journeys_tags %}
<div class="journey-actions">
    <h3>{% trans "Acciones" %}</h3>

    {% if request.user == journey.user %}
        <div class="btn-group-vertical">
          <a href="{% url "journeys:edit" journey.pk %}" class="btn btn-success">{% trans "Editar" %}</a>
          {% if not journey.needs_driver and not journey.disabled %}
              <a href="{% url "journeys:cancel" journey.pk %}" class="btn btn-danger">{% trans "Cancelar viaje" %}</a>
          {% else %}
              <a href="{% url "journeys:delete" journey.pk %}" class="btn btn-danger">{% trans "Borrar trayecto" %}</a>
              {% if has_recurrence %}
              <a href="{% url "journeys:delete-all" journey.pk %}" class="btn btn-danger">{% trans "Borrar todos los viajes" %}</a>
              {% endif %}
          {% endif %}
        </div>
    {% else %}
        {% journey_join_leave_button journey %}
    {% endif %}

</div>

upvcarshare/templates/journeys/blocks/details.description.html
{% load i18n %}
{% load journeys_tags %}

{% if not journey.needs_driver %}
    <h3>{% trans "Datos del transporte" %}</h3>
    <table class="table">
        <tbody>
        <tr>
            <th scope="row">{% trans "Conductor" %}</th>
            <td>{{ journey.driver.get_full_name }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Plazas libres" %}</th>
            <td>{{ journey.current_free_places }}/{{ journey.free_places }}</td>
        </tr>
        {% if journey.transport %}
            <tr>
                <th scope="row">{% trans "Datos del transporte" %}</th>
                <td>{{ journey.transport.description }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
{% elif is_fulfilled %}
    <h3>{% trans "Viajes enlazado" %}</h3>
    <p class="text-muted">{% trans "Te has apuntado a estos viajes de otros usuarios para cubrir tu necesidad." %}</p>
    {% for fulfilled_journey in fulfilled_by %}
        {% journey_item fulfilled_journey %}
    {% endfor %}
{% else %}
    <h3>{% trans "Viajes recomendados" %}</h3>
    <p class="text-muted">{% trans "Otros viajes ofrecidos por otros usuarios que encajan en tus criterios." %}</p>
    {% for recommended_journey in recommended %}
        {% journey_item recommended_journey %}
    {% empty %}
        <h4 class="text-muted">{% trans "No se ha encontrado transporte recomendado" %}</h4>
    {% endfor %}
{% endif %}

upvcarshare/templates/journeys/blocks/details.location.html
{% load i18n %}
{% load core_tags %}

<h3>
    {% if journey.kind == 0 %}
        {% trans "Origen" %}
    {% else %}
        {% trans "Destino" %}
    {% endif %}
</h3>
<p>{{ journey.residence.address }}</p>
<a href="{{ journey.residence.google_maps_link }}" target="_blank">
    <img src="{% google_static_map journey.residence.get_position_wgs84 300 300 14 %}" class="img-fluid">
</a>

upvcarshare/templates/journeys/blocks/details.passengers.html
{% load i18n %}

<h3>{% trans "Lista de pasajeros" %}</h3>
<table class="table">
    <tbody>
    {% for passenger in passengers %}
        <tr>
            <td>
                <img src="{{ passenger.user.get_avatar_url }}" class="img-circle avatar">
            </td>
            <td>
                {{ passenger.user.get_full_name }} <br />
                <small>{% trans "Unido el" %} {{ passenger.created }}</small>
            </td>
        </tr>
        <tr class="passenger-actions">
            {% if request.user == journey.driver and request.user == journey.user %}
                {% if passenger.status == CONFIRMED %}
                    <td colspan="2">
                        <form method="post" action="{% url "journeys:throw-out" passenger.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="return_to" value="{{ request.path }}">
                            <button type="submit" class="btn btn-danger">{% trans "Expulsar" %}</button>
                        </form>
                    </td>
                {% else %}
                    <td colspan="2">
                        <form method="post" action="{% url "journeys:confirm" passenger.pk %}" style="display: inline-block" {% if passenger.has_recurrence %}confirm-passenger-form{% endif %}>
                            {% csrf_token %}
                            <input type="hidden" name="return_to" value="{{ request.path }}">
                            <input type="hidden" name="user" value="{{ passenger.user.pk }}">
                            <button type="submit" class="btn btn-success">{% trans "Confirmar" %}</button>
                            <script type="text/ng-template" id="confirm-passenger.html">
                              <div class="modal-body text-xs-center">
                                <p class="lead">{% trans "El usuario ha solicitado apuntarse a más de una de las ocurrencias de este viaje" %}</p>
                                <button class="btn btn-lg btn-danger" type="button" ng-click="cancel($event)">{% trans "Cancelar" %}</button>
                                <button class="btn btn-lg btn-success" type="button" ng-click="continue($event)">{% trans "Confirmar para todos" %}</button>
                              </div>
                            </script>
                        </form>
                        <form method="post" action="{% url "journeys:reject" passenger.pk %}" style="display: inline-block" {% if passenger.has_recurrence %}reject-passenger-form{% endif %}>
                            {% csrf_token %}
                            <input type="hidden" name="return_to" value="{{ request.path }}">
                            <input type="hidden" name="user" value="{{ passenger.user.pk }}">
                            <button type="submit" class="btn btn-danger">{% trans "Rechazar" %}</button>
                            <script type="text/ng-template" id="reject-passenger.html">
                              <div class="modal-body text-xs-center">
                                <p class="lead">{% trans "El usuario ha solicitado apuntarse a más de una de las ocurrencias de este viaje" %}</p>
                                <button class="btn btn-lg btn-danger" type="button" ng-click="cancel($event)">{% trans "Cancelar" %}</button>
                                <button class="btn btn-lg btn-success" type="button" ng-click="continue($event)">{% trans "Rechazar para todos" %}</button>
                              </div>
                            </script>
                        </form>
                    </td>
                {% endif %}
            {% endif %}
        </tr>
    {% empty %}
        <p class="text-muted">{% trans "No hay pasajeros ahora mismo." %}</p>
    {% endfor %}
    </tbody>
</table>

upvcarshare/templates/journeys/blocks/join.all.one.html
{% load i18n %}
<script type="text/ng-template" id="join-all-one.html">
  <div class="modal-body text-xs-center">
    <p class="lead">{% trans "Este viaje tiene una o más repeticiones" %}</p>
    <button class="btn btn-lg btn-success" type="button" ng-click="one($event)">{% trans "Quiero apuntarme solo a este" %}</button>
    <button class="btn btn-lg btn-success" type="button" ng-click="all($event)">{% trans "Quiero apuntarme a todos los viajes" %}</button>
    <hr />
    <recurrence-calendar journey-id="[[journeyId]]" on-delete-day="removedDay(date)" on-add-day="addedDay(date)"></recurrence-calendar>
    <button class="btn btn-lg btn-success" type="button" ng-click="some($event)" style="margin-top: 10px"
            ng-class="{'disabled': selectedDates.length <= 0}">{% trans "Quiero seleccionar sólo algunas fechas" %}</button>
  </div>
</script>

upvcarshare/templates/journeys/blocks/search.form.html
{% load i18n %}
{{form.errors}}
<form method="post" action="" search-journey-form show-time="{{form.search_by_time.value}}">
    {% csrf_token %}
    <div class="form-group row">
      <label for="{{ form.departure_date.auto_id }}" class="col-sm-3 form-control-label">{{ form.departure_date.label }}</label>
      <div class="col-sm-3">
          <journey-date field-name="{{ form.departure_date.name }}" field-id="{{ form.departure_date.auto_id }}" value={{ form.departure_date.value }}></journey-date>
      </div>
      <div class="col-sm-6 form-check">
        <label class="form-check-label">
          <input type="checkbox" class="form-check-input" ng-click="toggleTime()" name="{{ form.search_by_time.name }}"
                 {% if form.search_by_time.value %}checked="checked"{% endif %}>
          {% trans "¿Especificar la hora del viaje?" %}
        </label>
      </div>
    </div>
    <div class="form-group row" ng-cloak ng-hide="showTime==='False'">
      <label for="{{ form.departure_date.auto_id }}" class="col-sm-3 form-control-label" style="padding-top:30px">{{ form.departure_time.label }}</label>
      <div class="col-sm-3">
          <journey-time field-name="{{ form.departure_time.name }}" field-id="{{ form.departure_time.auto_id }}"  value={{ form.departure_time.value }}></journey-time>
      </div>
      <label for="{{ form.time_window.auto_id }}" class="col-sm-3 form-control-label" style="padding-top:30px">{{ form.time_window.label }}</label>
      <div class="col-sm-3" style="padding-top:30px">
          {{ form.time_window }}
      </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <circle-map position-value="{{ form.position.value }}"
                        position-field="{{ form.position.name }}"
                        position-field-id="{{ form.position.auto_id }}"
                        radius-value="{{ form.distance.value }}"
                        radius-field="{{ form.distance.name }}"
                        radius-field-id="{{ form.distance.auto_id }}">
            </circle-map>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">{% trans "Buscar viajes" %}</button>
        </div>
    </div>
</form>